name: RMX First Workflow

on: workflow_dispatch

jobs: 
  rmx-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello World!"
      - name: Print Goodbye
        run: echo "Done - bye!"
